def select_media_type(var:str):
    """
    Select media type
    """
    match var:
        case '.txt':
            return 'text/plain'
        case '.html':
            return 'text/html'
        case '.htm':
            return 'text/html'
        case '.jpg':
            return 'image/jpeg'
        case '.jpeg':
            return 'image/jpeg'
        case '.png':
            return 'image/png'
        case '.gif':
            return 'image/gif'
        case '.ico':
            return 'image/x-icon'
        case '.svg':
            return 'image/svg+xml'
        case '.ttf':
            return 'application/octet-stream'
        case '.woff':
            return 'application/font-woff'
        case '.woff2':
            return 'application/font-woff2'
        case '.woff3':
            return 'application/font-woff3'
        case '.woff4':
            return 'application/font-woff4'
        case '.woff5':
            return 'application/font-woff5'
        case '.zip':
            return 'application/zip'
        case '.pdf':
            return 'application/pdf'
        case '.doc':
            return 'application/msword'
        case '.docx':
            return 'application/vnd.openxmlformats.wordprocessingml.document'
        case '.docm':
            return 'application/msword'
        case '.mp3':
            return 'audio/mpeg'
        case '.ogg':
            return 'audio/ogg'
        case '.oga':
            return 'audio/ogg'
        case '.webm':
            return 'video/webm'
        case '.wmv':
            return 'video/x-ms-wmv'
        case '.wm':
            return 'video/x-ms-wm'
        case '.mkv':
            return 'video/x-ms-mkv'
        case '.mp4':
            return 'video/mp4'
        case '.mov':
            return 'video/x-ms-wmv'
        case _:
            return 'application/octet-stream'
